<a href="https://colab.research.google.com/github/njha1999/Minor_Project_Covid_Classification/blob/main/Experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/Adarsh-Shrivastava-001/temp.git


Cloning into 'temp'...
remote: Enumerating objects: 3790, done.
remote: Total 3790 (delta 0), reused 0 (delta 0), pack-reused 3790
Receiving objects: 100% (3790/3790), 282.75 MiB | 43.43 MiB/s, done.
Checking out files: 100% (3766/3766), done.


In [3]:
import cv2
import os
import numpy as np
import pandas as pd


In [4]:

img_array = []
base = "temp/data_upload_v2/train/"
for img in os.listdir(base + "covid"):
    img_arr = cv2.imread(base + "covid/"+img, 0)
    img_arr = cv2.resize(img_arr, (128,128))
    img_arr = img_arr.flatten()
    img_arr = np.append(img_arr, 1)
    img_array.append(img_arr)
print(img_array)

[array([ 7,  7,  8, ..., 51, 39,  1]), array([  0,   0,   0, ..., 183, 173,   1]), array([ 2,  0,  0, ..., 49, 43,  1]), array([  4, 205, 179, ...,   1,   2,   1]), array([44,  1,  0, ..., 90, 71,  1]), array([  6,   5,   5, ..., 182, 162,   1]), array([7, 7, 8, ..., 5, 7, 1]), array([1, 1, 1, ..., 1, 1, 1]), array([0, 0, 0, ..., 0, 0, 1]), array([22, 23, 22, ..., 79, 73,  1]), array([ 4,  3,  4, ..., 67, 60,  1]), array([122, 124, 133, ...,  17,  14,   1]), array([ 10,  11,  10, ..., 189, 163,   1]), array([12,  9, 13, ...,  1,  2,  1]), array([ 1,  1,  1, ..., 38, 41,  1]), array([75, 48, 30, ..., 11, 12,  1]), array([  0,   0,   0, ..., 114, 135,   1]), array([ 7,  7,  8, ..., 12, 28,  1]), array([ 31,   0,   0, ..., 161, 173,   1]), array([57, 57, 57, ..., 57, 57,  1]), array([  1,   1,   1, ..., 186, 182,   1]), array([141, 136, 124, ..., 174, 152,   1]), array([12, 12, 13, ...,  8, 21,  1]), array([136, 137, 141, ..., 214, 217,   1]), array([1, 1, 1, ..., 1, 1, 1]), array([  2,  

In [5]:
print(len(img_array))

84


In [6]:
base = "temp/data_upload_v2/train/"
for img in os.listdir(base + "non"):
    img_arr = cv2.imread(base + "non/"+img, 0)
    img_arr = cv2.resize(img_arr, (128,128))
    img_arr = img_arr.flatten()
    img_arr = np.append(img_arr, 0)
    img_array.append(img_arr)
print(img_array)

[array([ 7,  7,  8, ..., 51, 39,  1]), array([  0,   0,   0, ..., 183, 173,   1]), array([ 2,  0,  0, ..., 49, 43,  1]), array([  4, 205, 179, ...,   1,   2,   1]), array([44,  1,  0, ..., 90, 71,  1]), array([  6,   5,   5, ..., 182, 162,   1]), array([7, 7, 8, ..., 5, 7, 1]), array([1, 1, 1, ..., 1, 1, 1]), array([0, 0, 0, ..., 0, 0, 1]), array([22, 23, 22, ..., 79, 73,  1]), array([ 4,  3,  4, ..., 67, 60,  1]), array([122, 124, 133, ...,  17,  14,   1]), array([ 10,  11,  10, ..., 189, 163,   1]), array([12,  9, 13, ...,  1,  2,  1]), array([ 1,  1,  1, ..., 38, 41,  1]), array([75, 48, 30, ..., 11, 12,  1]), array([  0,   0,   0, ..., 114, 135,   1]), array([ 7,  7,  8, ..., 12, 28,  1]), array([ 31,   0,   0, ..., 161, 173,   1]), array([57, 57, 57, ..., 57, 57,  1]), array([  1,   1,   1, ..., 186, 182,   1]), array([141, 136, 124, ..., 174, 152,   1]), array([12, 12, 13, ...,  8, 21,  1]), array([136, 137, 141, ..., 214, 217,   1]), array([1, 1, 1, ..., 1, 1, 1]), array([  2,  

In [7]:
print(len(img_array))

664


In [8]:
img_array_test = []
base2 = "temp/data_upload_v2/test/"
for img in os.listdir(base2 + "covid"):
    img_arr = cv2.imread(base2 + "covid/"+img, 0)
    img_arr = cv2.resize(img_arr, (128,128))
    img_arr = img_arr.flatten()
    img_arr = np.append(img_arr, 1)
    img_array_test.append(img_arr)
s = 0
for folder in os.listdir(base2 + "non"):
    for img in os.listdir(base2 + "non/" + folder):
        s+=1
        img_arr = cv2.imread(base2 + "non/"+folder+'/'+img, 0)
        img_arr = cv2.resize(img_arr, (128,128))
        img_arr = img_arr.flatten()
        img_arr = np.append(img_arr, 0)
        img_array_test.append(img_arr)

print(s)
print(len(img_array_test))

3000
3100


In [9]:
img_array = np.array(img_array)
img_array_test = np.array(img_array_test)
np.random.shuffle(img_array)
np.random.shuffle(img_array_test)

In [11]:
from sklearn.svm import SVC
clf = SVC()
clf.fit(img_array_test[:, :-1], img_array_test[:, -1])

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [12]:
print(img_array)


[[ 24  17  15 ... 219 218   0]
 [  4   5   7 ...   4   5   0]
 [  1   1   1 ...  38  41   1]
 ...
 [ 25  25  26 ...  88  87   1]
 [  2   2   2 ... 124 134   0]
 [ 17  17  17 ...  18   2   0]]


In [13]:
pred = clf.predict(img_array[:, :-1])
print(np.mean(pred == img_array[:,-1]))

0.9743975903614458


In [14]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(img_array[:,-1], pred))

[[580   0]
 [ 17  67]]


In [15]:
!pip install PyWavelets

In [16]:
import pywt

img_array = []
base = "temp/data_upload_v2/train/"
for img in os.listdir(base + "covid"):
    img_arr = cv2.imread(base + "covid/"+img, 0)
    img_arr = cv2.resize(img_arr, (128,128))
    img_arr = img_arr.flatten()
    a, d = pywt.dwt(img_arr, 'db2')
    img_arr = np.concatenate((a,d,img_arr))
    img_arr = np.append(img_arr, 1)
    img_array.append(img_arr)
print(img_array)

[array([ 9.89949494,  9.99422928, 11.18429898, ..., 51.        ,
       39.        ,  1.        ]), array([  0.,   0.,   0., ..., 183., 173.,   1.]), array([ 2.12132034,  0.70710678,  1.8625013 , ..., 49.        ,
       43.        ,  1.        ]), array([ 76.72108576, 190.63396081, 251.28172637, ...,   1.        ,
         2.        ,   1.        ]), array([47.02260095, 22.08688448,  0.        , ..., 90.        ,
       71.        ,  1.        ]), array([  8.13172798,   7.55403073,   7.07106781, ..., 182.        ,
       162.        ,   1.        ]), array([ 9.89949494, 10.1236388 , 10.60660172, ...,  5.        ,
        7.        ,  1.        ]), array([1.41421356, 1.41421356, 1.41421356, ..., 1.        , 1.        ,
       1.        ]), array([0., 0., 0., ..., 0., 0., 1.]), array([31.46625176, 32.0786242 , 30.08671338, ..., 79.        ,
       73.        ,  1.        ]), array([ 5.30330086,  4.82033795,  5.65685425, ..., 67.        ,
       60.        ,  1.        ]), array([173.241

In [17]:
base = "temp/data_upload_v2/train/"
for img in os.listdir(base + "non"):
    img_arr = cv2.imread(base + "non/"+img, 0)
    img_arr = cv2.resize(img_arr, (128,128))
    img_arr = img_arr.flatten()
    a, d = pywt.dwt(img_arr, 'db2')
    img_arr = np.concatenate((a,d,img_arr))
    img_arr = np.append(img_arr, 0)
    img_array.append(img_arr)
print(img_array)

[array([ 9.89949494,  9.99422928, 11.18429898, ..., 51.        ,
       39.        ,  1.        ]), array([  0.,   0.,   0., ..., 183., 173.,   1.]), array([ 2.12132034,  0.70710678,  1.8625013 , ..., 49.        ,
       43.        ,  1.        ]), array([ 76.72108576, 190.63396081, 251.28172637, ...,   1.        ,
         2.        ,   1.        ]), array([47.02260095, 22.08688448,  0.        , ..., 90.        ,
       71.        ,  1.        ]), array([  8.13172798,   7.55403073,   7.07106781, ..., 182.        ,
       162.        ,   1.        ]), array([ 9.89949494, 10.1236388 , 10.60660172, ...,  5.        ,
        7.        ,  1.        ]), array([1.41421356, 1.41421356, 1.41421356, ..., 1.        , 1.        ,
       1.        ]), array([0., 0., 0., ..., 0., 0., 1.]), array([31.46625176, 32.0786242 , 30.08671338, ..., 79.        ,
       73.        ,  1.        ]), array([ 5.30330086,  4.82033795,  5.65685425, ..., 67.        ,
       60.        ,  1.        ]), array([173.241

In [26]:
img_array_test = []
base2 = "temp/data_upload_v2/test/"
for img in os.listdir(base2 + "covid"):
    img_arr = cv2.imread(base2 + "covid/"+img, 0)
    img_arr = cv2.resize(img_arr, (128,128))
    img_arr = img_arr.flatten()
    a, d = pywt.dwt(img_arr, 'db2')
    img_arr = np.concatenate((a,d,img_arr))
    img_arr = np.append(img_arr, 1)
    img_array_test.append(img_arr)
s = 0
for folder in os.listdir(base2 + "non"):
    for img in os.listdir(base2 + "non/" + folder):
        s+=1
        img_arr = cv2.imread(base2 + "non/"+folder+'/'+img, 0)
        img_arr = cv2.resize(img_arr, (128,128))
        img_arr = img_arr.flatten()
        a, d = pywt.dwt(img_arr, 'db2')
        img_arr = np.concatenate((a,d,img_arr))
        img_arr = np.append(img_arr, 0)
        img_array_test.append(img_arr)

print(s)
print(len(img_array_test))
print()
print(len(img_array_test[0]))

3000
3100

32771


In [27]:
img_array = np.array(img_array)
img_array_test = np.array(img_array_test)
np.random.shuffle(img_array)
np.random.shuffle(img_array_test)

In [28]:
from sklearn.svm import SVC
clf = SVC()
clf.fit(img_array_test[:, :-1], img_array_test[:, -1])

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [29]:
pred = clf.predict(img_array[:, :-1])
print(np.mean(pred == img_array[:,-1]))

0.9563253012048193


In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(img_array[:,-1], pred))

[[580   0]
 [ 36  48]]
